### ISSUE TITLE
change order of episodes/slides

### ISSUE THREAD

**Issue by RobertArbon** [JGIBristol/robust-open-analysis-r#18]
- [ ] Update on deployed website (https://jean-golding-institute.github.io/robust-open-analysis-r/)

**Comment by RobertArbon** [comment]
1. Introduction - @NatalieThurlby 
* CoC 
* Instructions (show them where the website is).
* Flow-chart
* Housekeeping (mics off unless discussion).
* Breakout room introductions
* Zoom thumbs up/down
* Plan for the day - aim for workflow +1 Rproj

2. Reproducibilty - @NatalieThurlby 
* The reproducibility crisis
* Saving the world with reproducibility
* Being selfish 
* Creating a concept map of reproducibility
* Discussion
* Workflow usefulness

3. RStudio - @RobertArbon 0:45
* Pane walkthrough 
* Put all of this  in setup instructions and go through in class. 
* Practice writing in Rmarkdown.
* Rstudio can knit things
* Projects

* Useful function
  * Tab complete
  * Multiline
  * Debugger 
  * ..

4. RMarkdown - 0:30
* Use roar.Rproj
* use rmarkdown folder
* Talk about Directory. 

5. Github - 1:30
    1. Create net GH repo
    2. Create Github.Rproj with Version control. 
    3. Simple method
    4. Branches
    5. No PRs, Forks, except for quick overview.  

6.  Putting it all together. 
 * create roar.Rproj - using workflow. 
* use old_faithful folder.

**Comment by NatalieThurlby** [comment]
I am about to update the order of the intro template slides.

**Comment by NatalieZelenka** [comment]
Note: we'd like to keep the number of GitHub repos and Rstudio projects small to reduce confusion. And where we do need additional projects/repos, label them well and make sure there is a page where people can see which is which.
