### ISSUE TITLE
Update flowchart.

### ISSUE THREAD

**Issue by NatalieZelenka** [JGIBristol/robust-open-analysis-r#21]
- [x] Create updated flowchart as in comment below @RobertArbon 
- [x] Add to index
- [x] Add to each section with high-lighted box
- [x] Add to putting it all together

---
Notes: Don't want to do Rstudio project first because slightly more involved than creating GitHub first, and don't want to do SSH keys for same reason.

**Comment by RobertArbon** [comment]
Previously we did GitHub first:
1. Create Github repo
2. Create and link RStudio project [check github status]
3. Create directory structure
4. Edit .gitignore and readme and push
5. Create OSF project (pre-register?) and Link Github. 
6 - 9 As is. 

But we are now doing git first.
