### ISSUE TITLE
Update schedule on website

### ISSUE THREAD

**Issue by RobertArbon** [JGIBristol/robust-open-analysis-r#27]
- [ ] Check times on index page schedule
- [ ] Add schedule with breaks to welcome page (Overlap with issue #32)

**Comment by RobertArbon** [comment]
This should be done nearer the time after the various repos and github projects have been finalised.

**Comment by NatalieZelenka** [comment]
The schedule on [the index page](https://jean-golding-institute.github.io/robust-open-analysis-r/index.html) is created automatically from the YAML in the _episodes_rmd files, however, we will want to fill in the schedule on the welcome page (which will include breaks, etc).

**Comment by NatalieThurlby** [comment]
Closing this as it overlap with issue #32

**Comment by NatalieZelenka** [comment]
Closing this as it overlap with issue #32
